/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testdeployment.salesdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testdeployment.salesdb.Sales;
import com.testdeployment.salesdb.models.query.*;

public interface SalesdbQueryExecutorService {

    Page<SalesNativeSqlResponse> executeSales_NativeSQL(Pageable pageable);

    Downloadable exportSales_NativeSQL(ExportType exportType, Pageable pageable);

    Page<Sales> executeSales_HSQL(Pageable pageable);

    Downloadable exportSales_HSQL(ExportType exportType, Pageable pageable);

}


