/*Copyright (c) 2016-2017 wavemaker.com All Rights Reserved.
 This software is the confidential and proprietary information of wavemaker.com You shall not disclose such Confidential Information and shall use it only in accordance
 with the terms of the source code license agreement you entered into with wavemaker.com*/

package com.testdeployment.hrdb.service;

/*This is a Studio Managed File. DO NOT EDIT THIS FILE. Your changes may be reverted by Studio.*/


import org.springframework.data.domain.Page;
import org.springframework.data.domain.Pageable;

import com.wavemaker.runtime.data.export.ExportType;
import com.wavemaker.runtime.file.model.Downloadable;

import com.testdeployment.hrdb.Employee;
import com.testdeployment.hrdb.models.query.*;

public interface HrdbQueryExecutorService {

    Page<Employee> executeEmployee_HSQL(Pageable pageable);

    Downloadable exportEmployee_HSQL(ExportType exportType, Pageable pageable);

    Page<EmployeeNativeSqlResponse> executeEmployee_NativeSQL(Pageable pageable);

    Downloadable exportEmployee_NativeSQL(ExportType exportType, Pageable pageable);

}


